### ISSUE TITLE
Could you please explain the point of the equals function.

### ISSUE THREAD

**Issue by ateevnahar** [dxandbatista/A1-pt2#11]
to elaborate, equals is not a normally support queue function ie http://www.cplusplus.com/reference/queue/queue/

Why do you require it. I think it is unneeded and would love to hear you side. Thank you.

**Comment by dxandbatista** [comment]
Checking to see if two queues are equal would be a nice feature for the user using queues to have. Helps to check if references are set correctly as well. Just like if you'd want to see if two arrays are equal, the same train of thought applies here. Pretty straightforward to implement so I don't think it should be an issue on that end either.
