### ISSUE TITLE
Can you please not have your files inside the directory pt2? It is making docker much harder. Just have your files in the base git directory.

### ISSUE THREAD

**Issue by EanMcDonaldWojciechowski** [dxandbatista/A1-pt2#13]

**Comment by ateevnahar** [comment]
I think you can move things around in your submission (that is what I am going to do)

**Comment by EanMcDonaldWojciechowski** [comment]
The issue is that the makefile we were given pulls their code to grab the tests directly from this repo at the commit hash we specify. When it pulls it comes nested in the pt2 directory and now I am trying to update the makefile to accommodate this. It would be easier if the owners of this repo just remove the extra directory.

**Comment by ateevnahar** [comment]
Makes sense, I agree with that.

**Comment by dxandbatista** [comment]
Should be good to go
