### ISSUE TITLE
to-string tests wrongly return false. 

### ISSUE THREAD

**Issue by ateevnahar** [dxandbatista/A1-pt2#14]
t_true(strcmp(key1->to_string(), "Key Bob"));
this line of code will always evaluate false, as 
t_true(0); evaluates to a failed test. 
strcmp returns a 0 when the strings are equal.

**Comment by dxandbatista** [comment]
That's not in my test file?

**Comment by ateevnahar** [comment]
shit man, opened this is in the wrong repo. you good.
