### ISSUE TITLE
C++ Libraries should be removed

### ISSUE THREAD

**Issue by ryanheminway** [dxandbatista/A1-pt2#5]
Hi guys, thanks for being responsive so far! We found that your files are including <iostream> to use "std::cout" for printing. Unfortunately this is a C++ function and is prohibited for CwC files. For this assignment, both api and test files should be CwC, meaning this library dependency should be removed. A 'helper.h' is still allowed to include any required C++ functions, so you could move them there and then include "helper.h" in your CwC files. Or find another workaround such as using the c-library function 'printf'. Either way, would you mind making this change? Thanks

**Comment by dxandbatista** [comment]
Updated to use printf instead.

**Comment by ryanheminway** [comment]
Thanks! Some minor updates pertaining to the same problems: In "test-queue.cpp" you are currently including <stdio.h> after "object.h". This results in errors when compiling because "object.h" cannot find the definition for "size_t", among other things. If you include <stdio.h" before anything else, this problem resolves itself.

**Comment by dxandbatista** [comment]
Sorry for that, should be good to go now!
