### ISSUE TITLE
can you make your string and object class based on common specs 

### ISSUE THREAD

**Issue by ateevnahar** [dxandbatista/A1-pt2#6]
https://piazza.com/class/k51bluky59n2jr?cid=345

**Comment by ateevnahar** [comment]
mainly for fixing naming of meothds which have the same functionality

**Comment by dxandbatista** [comment]
We're seeing more people use Jan's utility classes,  so I've made changes to match his.

https://piazza.com/class/k51bluky59n2jr?cid=166

**Comment by dxandbatista** [comment]
I suggest you change yours as well and ask those that you got specs from to do the same, as that's what happened with us.

**Comment by ateevnahar** [comment]
The instructors are saying to use the piazza posts code which I linked as that is much more recent and updated. They link to it in recent posta unlike the code which you referenced.

**Comment by ateevnahar** [comment]
The functionality is not this issue I have but the naming. cmp vs compare in particular

**Comment by ateevnahar** [comment]
Also majority of the class is using the spec I linked so I would be helpful for us if your spec wasn’t an outlier.

**Comment by dxandbatista** [comment]
Changed and updated
